### PR TITLE
[feature] Join nearby options

### PR DESCRIPTION
**Pull request by mpcmarques**
Join (merge) nearby options, or multiple options attached same entity or coords. So it can show more than one interact at the same time (as a list),. For an interact point or entity that has multiple scripts attached to it.

It came with portuguese translations and some default events, but the merge options functionality is the achievement

### CODE REVIEW

**Comment by DemiAutomatic** [comment]
I actually have been wanting to implement this feature, but there is far too many changes in this PR for me to accept it.

**Comment by mpcmarques** [comment]
There is some breaking changes, instead of providing IDs to the interact, the id should be on each interact option.
Activedistance , bones and renderDistance as well.
Bone option was renamed to bones instead.

I will clean up files that were modified that arent needed for this feature to take place @Demigod916 
What I want to achieve is a fully replace of ox_target, even add compat files

**Comment by VIRUXE** [comment]
There's even a translation to Portuguese.

And changes should've been documented.

**Comment by mpcmarques** [comment]
> There's even a translation to Portuguese.
> 
> And changes should've been documented.

maybe you dint read it,  "It came with portuguese translations and some default events, but the merge options functionality is the achievement" but anyway, im canceling it

**Pull request closed without merging**
